platform :ios, '12.0'

target 'Plugin' do
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'RadarSDK', '~> 3.9.5'
end

target 'PluginTests' do
  use_frameworks!
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'RadarSDK', '~> 3.9.5'
end
